// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbDqn3pmDwjCCYm_YPx36YbSrhsuPmKls',
    appId: '1:807664219594:web:9d46bd5471a37bcd9f0b33',
    messagingSenderId: '807664219594',
    projectId: 'flash-chat-e02bd',
    authDomain: 'flash-chat-e02bd.firebaseapp.com',
    storageBucket: 'flash-chat-e02bd.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbDqn3pmDwjCCYm_YPx36YbSrhsuPmKls',
    appId: '1:807664219594:web:9d46bd5471a37bcd9f0b33',
    messagingSenderId: '807664219594',
    projectId: 'flash-chat-e02bd',
    authDomain: 'flash-chat-e02bd.firebaseapp.com',
    storageBucket: 'flash-chat-e02bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCat2wTyWjUeryLlTqAwjjyw9s-mChQY5g',
    appId: '1:807664219594:android:1daba89e71db0c9e9f0b33',
    messagingSenderId: '807664219594',
    projectId: 'flash-chat-e02bd',
    storageBucket: 'flash-chat-e02bd.firebasestorage.app',
  );

}